### ISSUE TITLE
I really like this idea, but there aren't any settings

### ISSUE THREAD

**Issue by byronbytes** [hotlandsoftware/Hotlands-Antivirus#1]
I could help make some settings!

**Comment by fathrma** [comment]
Yes, me too. I want to contribute this project, but how we can contact with the author?

**Comment by byronbytes** [comment]
I think the author left, I might fork it on my account

**Comment by hotlandsoftware** [comment]
Hi.

You can do whatever you want with the code. Keep in mind that this project was never finished, and I published it purely so people could learn & research from it. This is not a very good AV but I believe it could be if someone worked at i for long enough!

**Comment by byronbytes** [comment]
nice!!!!!!!!!!! I guess I'll fork it and do a redesign!
